### ISSUE TITLE
URL issue

### ISSUE THREAD

**Issue by arturek1666** [Ocelot5836/Pop-Out-Chat#2]
As soon as chat is in other window and i click on link i can't move in game,  With forces me to shutdown the game to fix it.

**Comment by Ocelot5836** [comment]
I tested with `/tellraw @p {"text":"Click Here","color":"aqua","clickEvent":{"action":"open_url","value":"https://www.google.com"},"hoverEvent":{"action":"show_text","contents":[{"text":"Open Test Link!"}]}}` and it worked fine. Please provide screenshots or logs so I can more easily solve this issue.

**Comment by arturek1666** [comment]
Looks like I have to check if any of other mods cause it.

**Comment by arturek1666** [comment]
Looks like I just have to: Move chat to second monitor, then open a link and then can't move. No error in logs
What's more it doesn't fill as smooth game when I separate chat it fills like stuff are slower ;)

**Comment by arturek1666** [comment]
I am no longer
